# Copyright (c) 2024 Cisco and/or its affiliates.
#
# This software is licensed to you under the terms of the Cisco Sample
# Code License, Version 1.1 (the "License"). You may obtain a copy of the
# License at
#
#                https://developer.cisco.com/docs/licenses
#
# All use of the material herein must be in accordance with the terms of
# the License. All rights not expressly granted by the License are
# reserved. Unless required by applicable law or agreed to separately in
# writing, software distributed under the License is distributed on an "AS
# IS" BASIS, WITH

default:
  image: localhost:5050/radkit-tools/pipeline:latest

stages:
  - deploy

deploy_l2_interface_config:
  stage: deploy
  script:
    - cd ansible
    - ansible-playbook -i radkit_devices.yml l2_interface_config-playbook.yml --limit radkit_description_meraki
  rules:
    - if: $CI_PIPELINE_SOURCE == "web" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $PIPELINE_NAME == "l2"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_PIPELINE_SOURCE == "push"
      changes:
        - ansible/device_vars/l2/*.yaml
        - ansible/vars/l2.yaml

deploy_vlan_config:
  stage: deploy
  script:
    - cd ansible
    - ansible-playbook -i radkit_devices.yml vlan_config-playbook.yml --limit radkit_description_meraki
  rules:
    - if: $CI_PIPELINE_SOURCE == "web" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $PIPELINE_NAME == "vlan"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_PIPELINE_SOURCE == "push"
      changes:
        - ansible/vars/vlans.yaml
        - ansible/device_vars/vlans/*.yaml
