vlans:
  - name: Vlan_10
    vlan_id: 10
    state: active
    shutdown: disabled
  - name: Vlan_20
    vlan_id: 20
    state: active
    shutdown: disabled
  - name: Vlan_30
    vlan_id: 30
    state: active
    shutdown: disabled
