# Copyright (c) 2024 Cisco and/or its affiliates.

# This software is licensed to you under the terms of the Cisco Sample
# Code License, Version 1.1 (the "License"). You may obtain a copy of the
# License at

#                https://developer.cisco.com/docs/licenses

# All use of the material herein must be in accordance with the terms of
# the License. All rights not expressly granted by the License are
# reserved. Unless required by applicable law or agreed to separately in
# writing, software distributed under the License is distributed on an "AS
# IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
# or implied.
---
- hosts: radkit_device_type_IOS_XE
  connection: cisco.radkit.network_cli
  vars:
    ansible_network_os: ios
  gather_facts: no
  tasks:
    - name: Include device-specific variables
      include_vars:
        file: "device_vars/{{ inventory_hostname }}.yaml"
      tags: include_vars

    - name: Merge VLAN interface configuration
      cisco.ios.ios_l2_interfaces:
        config:
          - name: "{{ item.interface.name }}"
            mode: "{{ item.interface.mode }}"
            access:
              vlan: "{{ item.interface.access.vlan | default(omit) }}"
            voice:
              vlan: "{{ item.interface.voice.vlan | default(omit) }}"
            trunk:
              allowed_vlans: "{{ item.interface.trunk.allowed_vlans | default(omit) }}"
              native_vlan: "{{ item.interface.trunk.native_vlan | default(omit) }}"
        state: merged
      loop: "{{ interfaces }}"
      when: inventory_hostname in groups['radkit_device_type_IOS_XE']
    - name: Merge interface configuration
      cisco.ios.ios_interfaces:
        config:
          - name: "{{ item.interface.name }}"
            description: "{{ item.interface.description }}"
            enabled: "{{ item.interface.enabled }}"
        state: merged
      loop: "{{ interfaces }}"
      when: inventory_hostname in groups['radkit_device_type_IOS_XE']
